Change tmp dir to HOME path
logzio/jaeger-logzio pull request #23
Opened 2021-06-09 13:41 UTC by yotamloe

2021-06-10 12:52 UTC, yyyogev approved these changes
Great work!

2021-06-13 07:35 UTC, Doron-Bargo requested changes
Please
1. Update readme with the new parameter
2. Add test as part of the initialization of queue path that the directory is accessible

2021-06-13 07:35 UTC, Doron-Bargo commented on store/config.go
> +	customQueueDirParam  = "CUSTOM_QUEUE_PATH"
fix liniting

2021-06-13 07:35 UTC, Doron-Bargo commented on store/config.go
> +	CustomQueueDir     string `yaml:"customQueueDir"`
fix linting

2021-06-13 08:42 UTC, yotamloe commented on store/config.go
> +	CustomQueueDir     string `yaml:"customQueueDir"`
@Doron-Bargo Please check out new [commit](https://github.com/logzio/jaeger-logzio/pull/23/commits/a23fb942b7dfd1e2355187932809a165b18a40a1)

2021-06-13 08:42 UTC, yotamloe commented on store/config.go
> +	customQueueDirParam  = "CUSTOM_QUEUE_PATH"
@Doron-Bargo Please check out new [commit](https://github.com/logzio/jaeger-logzio/pull/23/commits/a23fb942b7dfd1e2355187932809a165b18a40a1)

2021-06-14 14:56 UTC, Doron-Bargo approved these changes
Amazing work

2021-06-15 07:46 UTC, merged